import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <bool> device_opened;
    callback open-usb-device();
    callback open-serial-device();
    VerticalBox {
        Text {
            text: "Device: \{root.device_opened ? "Opened" : "Closed"}";
        }

        Button {
            text: "Open Device";
            clicked => {
                root.open-usb-device();
            }
        }

        Button {
            text: "Open Serial Device";
            clicked => {
                root.open-serial-device();
            }
        }
    }
}